---
# Gerenciamento de pacotes e atualização do sistema operacionao
- name: Atualizacao do Sistema Operacional
  yum: name=* state=latest update_cache=yes

- name: Instalacao de pacotes
  yum:
    name: "{{ packages }}"    # variavel
    state: latest
  vars:
    packages:                 # chamando a variavel packages definida em cima
      - net-tools
      - vim

# Configuracao de timezone
- name: Configurando timezone
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

...
